### ISSUE TITLE
request: SwiftUI Example

### ISSUE THREAD

**Issue by bradmartin** [eharrison/LottieTutorialWatchOS#1]
I've tried implementing this in a SwiftUI watchkit extension and can't seem to figure out the correct approach. Any help or guidance would be great.

**Comment by eharrison** [comment]
Hello Brad,

Sorry about the delay. For SwiftUI, please refer to this repo: https://github.com/eharrison/LottieTutorialWatchOS-SwiftUI

Let me know if you have any issues with it :)

**Comment by bradmartin** [comment]
Thanks for the reply. I'll check it out, spent last Friday trying to hack something together with SDWebImages and failed miserably 😄 .

Confirmed and working great. Thanks again.

**Comment by eharrison** [comment]
Haha, no worries, I hope the solution will work for you! If it doesn't, please let me know :)
After you commented on it, I realized that the blog post I wrote is no longer valid, the support changed a bit and actually got easier to use with SwiftPackageManager :)
