### ISSUE TITLE
Multiple lottie animations

### ISSUE THREAD

**Issue by DaemonChoejur** [eharrison/LottieTutorialWatchOS#2]
Hello, 
I would like some clarification in rendering multiple lottie animation (from file) in a scroll view fashion. 
Should I reuse the Lottie view models or create new view models for each lottie file? For example if I want to load 20 lottie file animations and present in a scroll view. 

Thank you.

**Comment by eharrison** [comment]
Hello, sorry for the late reply.

Yes, you will need to create a Row model and move the Animation logic inside the row. Call each row sending the animation url.
